
<?php
/**
 * @var \Study\RandomProducts\Block\RandomProduct $block
 */

?>

<h3>Random-products</h3>
<div class="random-products">
    <table>
        <tr>
            <th></th>
            <th></th>
        </tr>
        <?php foreach ($block->getRandomProduct() as $product):
            $url = $block->getImageUrl($product); ?>
            <tr>
                <td><a href="<?php echo $product->getProductUrl(); ?>"><img src="<?php echo $url?>"></a></td>
                <td><a href="<?php echo $product->getProductUrl(); ?>"><?php echo $product->getName(); ?></a>
                    <?php if($product->getData('show_yes_no')): ?>
                        <span><?php echo $product->getData('custom_dropdown'); ?></span>
                    <?php endif; ?>
                    <p><?php echo $block->getFormattedPrice($product->getData('price'))?></p>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>




